package com.cthulhu.events;

public enum EventType {
    ROLL, USE_LUCK, DEVELOP, PUSH, DEVELOP_SKILLS, INVESTIGATORS, //client events
    ROLL_RESULT, USE_LUCK_RESULT, DEVELOP_RESULT, PUSH_RESULT, DEVELOP_SKILLS_RESULT, INVESTIGATORS_RESULT //server events
}
