spring:
    artemis:
        mode: native
        host: localhost
        port: 61616
        user: admin
        password: admin

    datasource:
        url: jdbc:h2:mem:database
        username: sa
        password:
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
            path: /h2
        settings:
            web-allow-others = true
    liquibase:
        change-log: classpath:/db/changelog/db-changelog-master.json
    jpa:
        hibernate:
            ddl-auto: validate
        open-in-view: false
logging:
    level:
        org.apache.activemq.audit.base: WARN
        org.apache.activemq.audit.message: WARN

---
spring:
    profiles: test
    artemis:
        mode: embedded
        host: localhost
        port: 61616
        embedded:
            enabled: true
